[package]
name = "a32asm"
version = "2.0.0"
edition = "2021"
authors = ["Mathis Rech"]
description = "A32 assembler"
license = "MIT"

[dependencies]
termcolor = "1.1"
static_assertions = "1.1"
ahash = "0.7"
clap = { version = "3.2", features = ["derive"] }
langbox = "0.1"
